package com.jun.service.account.domain.templates;

import lombok.Data;

@Data
public class Template {
  public static String UserTemplate =
      "<table style=\"margin: 0; padding: 0; background-color: #f2f2f2; width: 100%!important; font-family: Arial,Helvetica,sans-serif; font-size: 12px; color: #444; line-height: 18px;\" border=\"0\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" bgcolor=\"#dcf0f8\">\n"
          + "    <tbody>\n"
          + "        <tr>\n"
          + "            <td style=\"font-family: Arial,Helvetica,sans-serif; font-size: 12px; color: #444; line-height: 18px; font-weight: normal;\" align=\"center\" valign=\"top\">\n"
          + "                <table style=\"margin-top: 15px; border-top: 3px solid #f54b24;\" border=\"0\" width=\"600\" cellspacing=\"0\" cellpadding=\"0\">\n"
          + "                    <tbody>\n"
          + "                        <tr class=\"CZhdm\" style=\"background: #fff;\">\n"
          + "                            <td id=\"m_3757859472090258022headerImage\" align=\"center\" valign=\"bottom\">\n"
          + "                                <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\n"
          + "                                    <tbody>\n"
          + "                                        <tr>\n"
          + "                                            <td style=\"padding: 15px 30px 0 30px;\" valign=\"top\" bgcolor=\"#FFFFFF\">\n"
          + "                                            </td>\n"
          + "                                            <td style=\"padding: 25px 30px 0 30px; font-size: 14px; text-align: right;\" bgcolor=\"#FFFFFF\">Bạn cần hỗ trợ? Vui l&ograve;ng gọi <strong>0383630495</strong></td>\n"
          + "                                        </tr>\n"
          + "                                    </tbody>\n"
          + "                                </table>\n"
          + "                            </td>\n"
          + "                        </tr>\n"
          + "                        <tr class=\"CZcm\" style=\"background: #fff;\">\n"
          + "                            <td>\n"
          + "                                <table>\n"
          + "                                    <tbody>\n"
          + "                                        <tr style=\"background: #fff;\">\n"
          + "                                            <td style=\"padding: 0 30px;\" align=\"left\" width=\"600\" height=\"auto\">\n"
          + "                                                <table width=\"600\">\n"
          + "                                                    <tbody>\n"
          + "                                                        <tr>\n"
          + "                                                            <td>\n"
          + "                                                                <h1 style=\"font-size: 18px; color: #000000; padding: 0 0 5px 0; font-weight: normal; line-height: 16px;\">Th&acirc;n ch&agrave;o <strong>#FULL_NAME#</strong>,</h1>\n"
          + "                                                                <p style=\"font-family: Arial,Helvetica,sans-serif; font-size: 14px; color: #000000; line-height: 18px; font-weight: normal;\">M&atilde; x&aacute;c minh của bạn l&agrave; <strong style=\"font-size: 18px;\">#CODE#</strong></p>\n"
          + "                                                            </td>\n"
          + "                                                        </tr>\n"
          + "                                                        <tr>\n"
          + "                                                            <td>\n"
          + "                                                                <p style=\"margin: 0; font-size: 14px; margin-bottom: 24px; line-height: 20px;\">Jun Shop tr&acirc;n trọng cảm ơn v&agrave; rất h&acirc;n hạnh được phục vụ bạn.\n"
          + "                                                                    <br />Đăng nhập v&agrave;o t&agrave;i khoản Jun Shop ngay b&acirc;y giờ để trải nghiệm th&ecirc;m.</p>\n"
          + "                                                            </td>\n"
          + "                                                        </tr>\n"
          + "                                                    </tbody>\n"
          + "                                                </table>\n"
          + "                                            </td>\n"
          + "                                        </tr>\n"
          + "                                    </tbody>\n"
          + "                                </table>\n"
          + "                            </td>\n"
          + "                        </tr>\n"
          + "                    </tbody>\n"
          + "                </table>\n"
          + "            </td>\n"
          + "        </tr>\n"
          + "    </tbody>\n"
          + "</table>";
}
