spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/jun_database
    web:
      pageable:
        size-parameter: size
        page-parameter: page
        default-page-size: 10
        max-page-size: 100
      sort:
        sort-parameter: sort
  kafka:
    listener:
      type: batch
      ack-mode: manual_immediate
      missing-topics-fatal: false
    bootstrap-servers: 127.0.0.1:9092
    topic:
      replication-factor: 1
      num-partitions: 1
    producer:
      acks: all
      retries: 100
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://127.0.0.1:8081
        specific.avro.reader: true
      template:
        default-topic: test
    consumer:
      enable-auto-commit: false
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        request:
          timeout:
            ms: 12000000
        schema.registry.url: http://127.0.0.1:8081
        specific.avro.reader: true
      max-poll-records: 300
      fetch-max-wait: 3000 # 10s
      fetch-min-size: 50000000 #50mb
      group-id: "jun-service"

#    proxy-target-class: true
#  main:
#    allow-bean-definition-overriding: true
debug: true
server:
  port: 8093
  error:
    include-stacktrace: on_trace_param

jwt:
  secret: abajihi3hi234hihi3f09acn
  token-expire-time: 7200
  token-refresh-expire-time: 1296000
    



